#email: hi@ratan.me
#title: blog.ratan.me
#baseurl: "http://blog.ratan.me" # the subpath of your site, e.g. /blog
url: "http://blog.ratan.me" # the base hostname & protocol for your site
#twitter_username: imratan19
#github_username:  jekyll
#excerpt_separator: <!--more--> 

# Build settings
markdown: kramdown
permalink: /:title
theme: minima

gems: [jekyll-paginate]
gems: [jekyll-paginate, jekyll-coffeescript, jekyll-watch, jekyll-assets]
paginate: 3 # number of posts you want per page
paginate_path: "/blog/"